module4task1,2,3,4
js-tasks-ru/jsbasic-20220113_534 pull request #3
Opened 2022-02-04 10:24 UTC by KaterinaKrasnitskaya

2022-02-04 10:25 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-04 15:51 UTC, SinimaWath requested changes

2022-02-04 15:51 UTC, SinimaWath commented on 3-module/1-task/index.js
> +    });
давай попробуем использовать map
- получится меньше кода

2022-02-04 15:51 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    })
давай попробуем разбить на 2 шага:
- filter
- map

2022-02-04 15:51 UTC, SinimaWath commented on 3-module/2-task/index.js
> +    return newmassiv;
нет необходимости во временной переменной `newmassiv `.

можно сразу вернуть результат: `return arr.filter(item => (item >= a && item <= b))`

2022-02-06 06:23 UTC, KaterinaKrasnitskaya commented on 3-module/1-task/index.js
> +    });
Добрый! Вчера пол вечера смотрела на главу учебника про map.
Есть сложность:(
Если я передаю массив - все работает.
Если массив объектов, как будто он этой вложенности не видит:( (Не видит содержание объектов внутри массива).
Напиши пожалуйста как должен выглядеть код:).

2022-02-07 16:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-08 12:27 UTC, SinimaWath commented on 3-module/1-task/index.js
> +    });
`users.map(item => item.name)`

2022-02-10 11:29 UTC, SinimaWath commented
ДАвай поправим остальные замечания

2022-02-10 16:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-02-11 18:53 UTC, SinimaWath approved these changes
все ок!

2022-02-11 18:53 UTC, merged